"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 01:24:53.791254

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("area", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amenities", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_table(
        "addons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("property_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("price_unit", sa.String(), nullable=False),
        sa.CheckConstraint(
            "price_unit IN ('per_booking', 'per_night', 'per_guest', 'per_guest_per_night')", name="addon_price_unit"
        ),
        sa.CheckConstraint("price > 0", name="addon_price_positive"),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addons_property_id"), "addons", ["property_id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("property_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('cancellation', 'check_in_out', 'children', 'pets', 'smoking', 'payment')", name="policy_kind"
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("property_id", "kind"),
    )
    op.create_table(
        "room_types",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("property_id", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("base_occupancy", sa.Integer(), nullable=False),
        sa.Column("max_occupancy", sa.Integer(), nullable=False),
        sa.Column("extra_guest_fee", sa.Integer(), nullable=False),
        sa.Column("amenities", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("base_occupancy >= 1 AND base_occupancy <= max_occupancy", name="occupancy_range"),
        sa.CheckConstraint("extra_guest_fee >= 0", name="extra_guest_fee_non_negative"),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_room_types_property_id"), "room_types", ["property_id"], unique=False)
    op.create_table(
        "turns",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("reply", sa.Text(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_action", sa.String(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("conversation_id", "seq"),
    )
    op.create_table(
        "booking_holds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("room_type_id", sa.String(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("guest_name", sa.Text(), nullable=False),
        sa.Column("quote", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('held', 'released')", name="hold_status"),
        sa.CheckConstraint("check_out > check_in", name="hold_dates"),
        sa.CheckConstraint("rooms >= 1", name="hold_rooms"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_active_holds",
        "booking_holds",
        ["room_type_id", "check_in", "check_out"],
        unique=False,
        postgresql_where=sa.text("status = 'held'"),
    )
    op.create_index(op.f("ix_booking_holds_conversation_id"), "booking_holds", ["conversation_id"], unique=False)
    op.create_table(
        "room_inventory",
        sa.Column("room_type_id", sa.String(), nullable=False),
        sa.Column("stay_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("units_open", sa.Integer(), nullable=False),
        sa.CheckConstraint("rate > 0", name="rate_positive"),
        sa.CheckConstraint("units_open >= 0", name="units_open_non_negative"),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
        ),
        sa.PrimaryKeyConstraint("room_type_id", "stay_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_inventory")
    op.drop_index(op.f("ix_booking_holds_conversation_id"), table_name="booking_holds")
    op.drop_index("ix_active_holds", table_name="booking_holds", postgresql_where=sa.text("status = 'held'"))
    op.drop_table("booking_holds")
    op.drop_table("turns")
    op.drop_index(op.f("ix_room_types_property_id"), table_name="room_types")
    op.drop_table("room_types")
    op.drop_table("policies")
    op.drop_index(op.f("ix_addons_property_id"), table_name="addons")
    op.drop_table("addons")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_table("properties")
    op.drop_table("conversations")
    # ### end Alembic commands ###
